# Generated by Django 4.2.7 on 2023-11-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('idAdministrateur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(default='Nom', max_length=45)),
                ('Prenom', models.CharField(default='Prenom', max_length=100)),
                ('Email', models.EmailField(default='email@gmail.com', max_length=254, unique=True)),
                ('Password', models.CharField(default='1234', max_length=45)),
                ('Numero_tel', models.CharField(default='0710069551', max_length=45, unique=True)),
                ('Date_inscription', models.DateField(auto_now_add=True)),
                ('Date_fin', models.DateTimeField(blank=True, null=True)),
                ('Image', models.ImageField(default='', upload_to='admin_images/')),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'Administrateur',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(default='Nom', max_length=45)),
                ('Prenom', models.CharField(default='Prenom', max_length=100)),
                ('Email', models.EmailField(default='email@gmail.com', max_length=254, unique=True)),
                ('Password', models.CharField(default='1234', max_length=45)),
                ('Numero_tel', models.CharField(default='0710069551', max_length=45, unique=True)),
                ('Image', models.ImageField(default='', upload_to='client_images/')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('idVoiture', models.AutoField(primary_key=True, serialize=False)),
                ('Marque', models.CharField(default='Marque', max_length=45)),
                ('Modele', models.CharField(default='Modele', max_length=45)),
                ('Prix_location_jour', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('Etat_voiture', models.CharField(default='', max_length=45)),
                ('vitesse', models.FloatField(default=200, max_length=200)),
                ('Killometrage', models.CharField(default='Illimitee', max_length=45)),
                ('Equipement_voiture', models.CharField(default='', max_length=45)),
                ('Document_requis', models.CharField(default='Permis de conduire', max_length=45)),
                ('disponible', models.BooleanField(default=True, help_text='Indique si la voiture est disponible pour la location')),
                ('Administrateur_idAdministrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.administrateur')),
                ('Client_idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.client')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'db_table': 'Voiture',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idLocation', models.AutoField(primary_key=True, serialize=False)),
                ('Date_debut', models.DateTimeField(auto_now_add=True)),
                ('Date_fin', models.DateTimeField(blank=True, null=True)),
                ('Cout_total', models.DecimalField(decimal_places=2, default=200, max_digits=5)),
                ('Note', models.IntegerField(default=1)),
                ('Administrateur_idAdministrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.administrateur')),
                ('Client_idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='myapp.client')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idImage', models.AutoField(primary_key=True, serialize=False)),
                ('Image_voiture', models.ImageField(default='', upload_to='voiture_images/')),
                ('Voiture_idVoiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.voiture')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'Image',
            },
        ),
    ]
