# Generated by Django 4.2.7 on 2023-11-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Voiture_idVoiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.voiture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='condition_general',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nombre_jour',
            field=models.IntegerField(default=1),
        ),
    ]
