# Generated by Django 4.2.7 on 2023-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_location_voiture_idvoiture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='Garantir_voiture',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='location',
            name='Cout_total',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='Prix_location_jour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='vitesse',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, max_length=200),
        ),
    ]
