# Generated by Django 4.2.7 on 2023-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_voiture_garantir_voiture_alter_location_cout_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Nom',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='Numero_tel',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Password',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='Prenom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
