# Generated by Django 4.2.7 on 2023-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_client_email_alter_client_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Image',
            field=models.ImageField(blank=True, default='', upload_to='client_images/'),
        ),
    ]
