# Generated by Django 4.2.7 on 2023-11-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='Date_fin',
        ),
    ]
