# Generated by Django 4.2.7 on 2024-02-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_administrateur_date_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='Equipement_voiture',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='Etat_voiture',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='Garantir_voiture',
        ),
    ]
