# Generated by Django 4.2.7 on 2024-02-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_administrateur_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='vitesse',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, max_length=1000),
        ),
    ]
